[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10.36", features = ["vendored"] }
tokio = { version = "1.0.0", features = ["full", "tracing"] }
